### ISSUE TITLE
Create variable for upload_results based on target

### ISSUE THREAD

**Issue by ataft** [flexanalytics/dbt_observability#11]
Currently, each project must define the on-run-end statement and logic to run only on 'prod', like this:
```
on-run-end:
  - "{% if target.name == 'prod' %}
        {{ dbt_observability.upload_results(results) }}
     {% endif %}"
```

We should fix this so projects only need to configure:
```
on-run-end: "dbt_observability.upload_results(results)"
```

Then, have a variable like "dbt_observability:target" that we can set to 'prod' or other values (maybe multiple?)

**Comment by MiConnell** [comment]
Addressed in #20 with the new `"dbt_observability:environments"` variable
