### ISSUE TITLE
The `v2-stable` tag did not update

### ISSUE THREAD

**Issue by ataft** [flexanalytics/dbt_observability#37]
The `v2-stable` tag did not update with the 2.7.5 release

![image](https://github.com/user-attachments/assets/5f209ca7-129e-406e-89e5-a4848c6c6a2e)

**Comment by MiConnell** [comment]
There was a hardcoded version check instead of a non-blank check (`major == 1` instead of `major != ''`). This has been corrected and the major tag has been updated. 
![image](https://github.com/user-attachments/assets/e574d226-5f9e-4469-8240-70ae84d9ec7a)
