### ISSUE TITLE
Marts Run order and Materialization

### ISSUE THREAD

**Issue by ataft** [flexanalytics/dbt_observability#7]
Marts have to be materialized as views because they are created during the dbt build, whereas the upload of artifacts happens after this `on-run-end`. The only way to materialize the mart models as tables will be to have it as a separate job and/or package that runs after the regular job.

**Comment by MiConnell** [comment]
Closing as this has been achieved via the new [dbt_observability_marts](https://github.com/flexanalytics/dbt_observability_marts) package
